name: Build-Test-Deploy

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 21 * * *'

jobs:
  Build-job:
    runs-on: windows-latest
    name: Making builds
    steps:
      - uses: actions/checkout@v1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge

  Test-job1:
    runs-on: windows-latest
    name: Test1
    needs: Build-job
    if: github.ref != 'refs/heads/production'
    steps:
      - uses: actions/checkout@v1
      - name: Test1
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha
      - run: npm test

  Test-job2:
    runs-on: windows-latest
    name: Test2
    needs: Build-job
    if: github.ref != 'refs/heads/production'
    steps:
      - uses: actions/checkout@v1
      - name: Test1
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha chai --save-dev
      - run: npm test

  Test-job3:
    runs-on: windows-latest
    name: Test3
    needs: Build-job
    if: github.ref != 'refs/heads/production'
    steps:
      - uses: actions/checkout@v1
      - name: Test3
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha chai --save-dev
      - run: npm install unit.js
      - run: npm test

  Deploy-job:
    runs-on: windows-latest
    needs: [Test-job1, Test-job2, Test-job3]
    name: Deployment
    steps:
      - uses: actions/checkout@v1
      - name: deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
      - run: surge ./ ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}
