name: Build-Test-Deploy

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 21 * * *'

jobs:
  Build-job:
    runs-on: windows-latest
    name: Making builds
    steps:
      - uses: actions/checkout@v1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge

  Test-job1:
    runs-on: windows-latest
    name: Test1
    needs: Build-job
    if: github.ref != 'refs/heads/production'
    steps:
      - uses: actions/checkout@v1
      - name: Test1
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha
      - run: npm test

  Test-job2:
    runs-on: windows-latest
    name: Test2
    needs: Build-job
    if: github.ref != 'refs/heads/production'
    steps:
      - uses: actions/checkout@v1
      - name: Test1
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha chai --save-dev
      - run: npm test

  Test-job3:
    runs-on: windows-latest
    name: Test3
    needs: Build-job
    if: github.ref != 'refs/heads/production'
    steps:
      - uses: actions/checkout@v1
      - name: Test3
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha chai --save-dev
      - run: npm install unit.js
      - run: npm test

  Deploy-job:
    runs-on: windows-latest
    needs: [Test-job1, Test-job2, Test-job3]
    name: Deployment
    steps:
      - uses: actions/checkout@v1
      - name: deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
      - run: surge ./ ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}

  Postdeploy-Testing:
    runs-on: windows-latest
    needs: Deploy-job
    name: Curl-Testing
    steps:
      - uses: actions/checkout@v1
      - name: Curl-Testing
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install curl
      - run: curl -Is ${{secrets.SURGE_DOMAIN}} | head -n 1

  Notify-on-email:
    runs-on: windows-latest
    if: always()
    needs: [Postdeploy-Testing, Deploy-job, Test-job3, Test-job2, Test-job1, Build-job]
    name: EmailNotify
      steps:
        - name: Send mail
          uses: dawidd6/action-send-mail@v2
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: Github Actions job result
            body: Workflow status of ${{github.repository}} 1)Buildjob- ${{needs.Build-job.result}}  2)Test1- ${{needs.Test-job1.result}} 3)Test2- ${{needs.Test-job2.result}} 4)Test3- ${{needs.Test-job3.result}} 5)Deployment- ${{needs.Deploy-job.result}} 6)PostDeployment- ${{needs.Postdeploy-Testing.result}}
            to: musaababs@gmail.com
            from: its-Saab
